---
- name: Start watcharr stack
  when: watcharr_enabled is true
  block:
    - name: Make sure nas default network exists
      community.docker.docker_network:
        name: nas
        state: present

    - name: Ensure watcharr compose directory exists
      ansible.builtin.file:
        path: '{{ nas_docker_compose_dir }}/watcharr'
        state: directory
        owner: '{{ watcharr_uid }}'
        group: '{{ watcharr_gid }}'
        mode: "0775"

    - name: Copy watcharr compose template
      ansible.builtin.template:
        src: '{{ role_path }}/templates/docker-compose.yml'
        dest: '{{ nas_docker_compose_dir }}/watcharr/docker-compose.yml'
        owner: '{{ watcharr_uid }}'
        group: '{{ watcharr_gid }}'
        mode: "0775"

    - name: Start watcharr stack
      community.docker.docker_compose_v2:
        project_src: '{{ nas_docker_compose_dir }}/watcharr'
        state: present
        pull: missing
        remove_orphans: true

- name: Stop watcharr stack
  when: watcharr_enabled is false
  block:
    - name: Tear down watcharr stack
      community.docker.docker_compose_v2:
        project_src: '{{ nas_docker_compose_dir }}/watcharr'
        state: absent

    - name: Remove watcharr compose directory
      ansible.builtin.file:
        path: '{{ nas_docker_compose_dir }}/watcharr'
        state: absent
