---
- name: Start tdarr stack
  when: tdarr_enabled is true
  block:
    - name: Make sure nas default network exists
      community.docker.docker_network:
        name: nas
        state: present

    - name: Ensure tdarr compose directory exists
      ansible.builtin.file:
        path: '{{ nas_docker_compose_dir }}/tdarr'
        state: directory
        owner: '{{ tdarr_owner_uid }}'
        group: '{{ tdarr_owner_gid }}'
        mode: "0775"

    - name: Copy tdarr compose template
      ansible.builtin.template:
        src: '{{ role_path }}/templates/docker-compose.yml'
        dest: '{{ nas_docker_compose_dir }}/tdarr/docker-compose.yml'
        owner: '{{ tdarr_owner_uid }}'
        group: '{{ tdarr_owner_gid }}'
        mode: "0775"

    - name: Start tdarr stack
      community.docker.docker_compose_v2:
        project_src: '{{ nas_docker_compose_dir }}/tdarr'
        state: present
        pull: missing
        remove_orphans: true

- name: Stop tdarr stack
  when: tdarr_enabled is false
  block:
    - name: Tear down tdarr stack
      community.docker.docker_compose_v2:
        project_src: '{{ nas_docker_compose_dir }}/tdarr'
        state: absent

    - name: Remove tdarr compose directory
      ansible.builtin.file:
        path: '{{ nas_docker_compose_dir }}/tdarr'
        state: absent
