arr_stack_enabled: false

arr_stack_puid: "{{ nas_docker_uid }}"
arr_stack_pgid: "{{ nas_docker_gid }}"
arr_stack_timezone: "America/Sao_Paulo"

arr_stack_sonarr_port: "8989"
arr_stack_radarr_port: "7878"
arr_stack_bazarr_port: "6767"
arr_stack_jackett_port: "9117"
arr_stack_prowlarr_port: "9696"
arr_stack_recomendarr_port: "3030"
arr_stack_seerr_port: "5055"
arr_stack_profilarr_port: "6868"
arr_stack_autobrr_port: "7474"

arr_stack_sonarr_config_dir: "{{ nas_docker_directory }}/sonarr"
arr_stack_radarr_config_dir: "{{ nas_docker_directory }}/radarr"
arr_stack_bazarr_config_dir: "{{ nas_docker_directory }}/bazarr/config"
arr_stack_jackett_config_dir: "{{ nas_docker_directory }}/jackett"
arr_stack_prowlarr_config_dir: "{{ nas_docker_directory }}/prowlarr"
arr_stack_recomendarr_config_dir: "{{ nas_docker_directory }}/recomendarr"
arr_stack_seerr_config_dir: "{{ nas_docker_directory }}/seerr"
arr_stack_profilarr_config_dir: "{{ nas_docker_directory }}/profilarr"
arr_stack_autobrr_config_dir: "{{ nas_docker_directory }}/autobrr"

arr_stack_series_dir: "{{ nas_library_dir }}"
arr_stack_movies_dir: "{{ nas_library_dir }}"

arr_stack_downloads_dir: "{{ nas_download_dir }}"
arr_stack_seedbox_downloads_dir: "{{ seedbox_downloads_dir }}"
